/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _AGENDA_H_RPCGEN
#define _AGENDA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct params {
	char *nome;
	char *telefone;
	char *endereco;
	char *aux;
};
typedef struct params params;

#define AGENDA_PROG 1111111
#define AGENDA_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define INSERT 1
extern  int * insert_1(params *, CLIENT *);
extern  int * insert_1_svc(params *, struct svc_req *);
#define SEARCH 2
extern  char ** search_1(params *, CLIENT *);
extern  char ** search_1_svc(params *, struct svc_req *);
#define UPDATE 3
extern  int * update_1(params *, CLIENT *);
extern  int * update_1_svc(params *, struct svc_req *);
#define DELETE 4
extern  int * delete_1(params *, CLIENT *);
extern  int * delete_1_svc(params *, struct svc_req *);
extern int agenda_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define INSERT 1
extern  int * insert_1();
extern  int * insert_1_svc();
#define SEARCH 2
extern  char ** search_1();
extern  char ** search_1_svc();
#define UPDATE 3
extern  int * update_1();
extern  int * update_1_svc();
#define DELETE 4
extern  int * delete_1();
extern  int * delete_1_svc();
extern int agenda_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_params (XDR *, params*);

#else /* K&R C */
extern bool_t xdr_params ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_AGENDA_H_RPCGEN */
