/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "agenda.h"

bool_t
xdr_params (XDR *xdrs, params *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->nome, 30))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->telefone, 30))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->endereco, 30))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->aux, 30))
		 return FALSE;
	return TRUE;
}
